### ISSUE TITLE
Could you please add some info about the env / system / packages requirements?

### ISSUE THREAD

**Issue by ragegage** [dawid-januszkiewicz/HE#1]
I know this is a personal project, but I'm very interested in running it locally :)
When I tried to, the code execution failed since I'm missing some required python packages and potentially don't have the right code environment.
Thank you for making this!

**Comment by alicja-januszkiewicz** [comment]
I'm flattered that anyone actually took an interest. I'm guessing you've played the original?

I'm not even sure whether the main branch works out of the box. I will look into getting it to work this week and provide a list of packages. System-wise I ran this on Linux, first Fedora and then Arch after I ran into issues with OpenGL and Wayland, but the main branch runs on pysdl2. Perhaps it is sdl2-gfx that you're missing? Anyway I will try to produce the full list over the week.

**Comment by alicja-januszkiewicz** [comment]
I managed to get it to work today and the main branch seems to be playable out of the box. There are different gameplay settings you can modify like the map size, no of players and map shape. There's no gui yet so you'd have to tinker with the code to change these.

To install:
```
python -m venv env
source env/bin/activate
pip install pysdl2 pysdl2-dll
```
Installing pysdl2-dll should provide the sdl2-gfx and sdl2-tff modules. If it doesn't work or the package doesn't exist on your system you can try compiling these from source. There might be other ways but I don't understand this stuff very well. See https://pysdl2.readthedocs.io/en/rel_0_9_7/install.html for reference.

Let me know if you manage to get it to work :) 

My system configuration for reference:
Arch Linux with Python 3.9.7
PySDL2==0.9.9
pysdl2-dll==2.0.16

**Comment by ragegage** [comment]
I have indeed played the original, and started making my own version of it once Flash support ran out.

Someone else working on a Unity version contacted me to ask about the army morale logic in my version and so I started looking around at other versions and found yours, which looked much better than mine 😅 

Just got it working thanks to your instructions (on a mac), and it's great! I appreciate the logging :)
